language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

before_script:
  - yarn mock &
  - "sleep 5" # Wait for the mock server to start
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ] && ./scripts/update-submodule.sh'

script:
  - yarn test
  - yarn lint
