language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- echo $GH_TOKEN
- yarn test
- yarn lint
env:
  global:
  - secure: edSsQaFohuIPdoIWcRIc+DsLNgFXLhZ/EBtE+pNUXOZjZb6Ja58vdQ2MEI+TNycYwUCtrhIElA/a7qmyDufLGnQrVBDV0tR+SQVwx8O+o/xJw8OvKgsAGuNYFXZiXd24m2A1Gz6KF+lv6XJbNvmBInm5fMyONRtCKu91KHiLz3qnYZMV9leao9x/uNXpyqFGhoOhPAqvsLL/s6JDXVWh8QJ+8WJJQ5qg/yxR6hx7ZrLACxiTRiMkOLUaxpesB0qucOB4qWkEKFP78gGhh6wQg0sSpOemlVcXWGwg5FE7aqZLazGcC/C9YBCEghI+Jsqul1ObiGtVrImP39lY63177dBJtYb7030GBIoa1vxkzAQtspJolsmIK/YK1OddSyGd64oIj2Z/xgVB5rYLInT+lzXj3R7kaQ4H3tra38oEqEm020CD5O0/KNiSdso7eWHlPypNZIXgfZ6YaZuJIS0EjZlS7oOc1mVYHN2YpLiGwX/9tQP99jl0dKoyxCIAMdUfvVMLlAnUEqY4/JagtmzERri4wDokcfOjjF3OboVHJbNjSBmXZTV2TS0I0viXX6x+lYY51Of1+LQJwg15iV5Ud36Czdp93EKBdWViDwVHraXCE3HS8acK5sm2HqAqcIYaFcXgLwfww74lraKPR9/TW2riWYdIEBn0ZO86ap+1qa4=
