language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- echo $GH_TOKEN
- yarn test
- yarn lint
env:
  global:
  - secure: RmaYpXRbTOUKUi7ko2DIcusx9HPHR+AenxE2uuA2xDudFbVIkni/48utMFntr5vRqp8FaxaGm4rqef77Qz3PiEF0j/FvLvPayFxD2IwNeiqMO0mxJCaxLV1t193QZeTBirH5cOuSOPS0+HOBp77xzwIyOBXv1bM2QAbvhkpAzi0NfQLafI54y34zCeW2er2DIDnQaqyeikeLnUEbS6A+wCKBtragJWad63bG4tVr0Ew9aW2li67ilS/kAC2Dsh61CEpD2UHdnZ0bAdA/eV2G+rCNXMMF8Oo1psfzM71tEOY/mBGfQETNdkE7YQ9rcGHoEcUzrPPNgUQgo60bxm4AKSv6CPfmqedFeoWdGOaY8YlcGw50iGw70o+KmVUfpcsqEIdPVcD1Jv6nyCnip7p899+sTZWRr370fh927NzdgP6rqTWQ1s6p8zhrTONLhZIXxbTSi2bIjLnAJyNXnzRHuaqqEs6nzZb0cpipNcUQGUkV4AWQ7y/3R1qhehyl7r+WSImGUhHKsSGq148aAhbEpo0NmaBfQNO6kxPCXY0p+df2tGbq+gYJB0yCDpEgdEbJ8VIThm+wkXhq6jux4q5xy86UUWdllFyqg8nRgdI0heErvHOitNntif33bAfOhf2kZ6OBEdFcRVjLQASqIgCl630CitbNHJy+MpNdh6iWL2M=
