language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules
    - backend
    - vendor/bundle

before_install:
  # Setup backend
  - npm run mock
  - "sleep 5" # Wait for the Rails app to start
  - "cd .."

install:
  - npm install

script:
  - npm test
