language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- yarn test
- yarn lint
env:
  global:
    secure: WAC2MZ9tBI6NiBAqg/+OW25HTBqITC+E6t2qRJrbsTwttAVjUjEMb4S73TFHN7bUVQ02n2ap2Nx4yW6FNhtdK507Rh67vZWo1MuJBh6ZgPJxjpU0bkIsKmP8/b7BMilRJnbwMRsf+d1E0nWz6vgnGbsZLArOSGrvCX5ccl+AiPiCfTWbOBolaAUeZcDuDu+2sn2PO5zrbo9l2+DfH0BnysVZrnD8v/AUcPQ+28K4ehJ4pU99yIMMKKrkm8dqcIFllmFOJsXKl6g+y8nupoPFZMT1BTxm3vjfgCcpdyTfhO+os/MO6TJTmTZ00nQzc8lNWGXG8AhcaRzbzDz6C73xx97fQ5AqPt53BErzZsUwGQR62nSGyMXyE9VytntkXJJ7vxxCLq5BWg53awaVNWPdfuOAe4gGzeQfsWrMv8pm9nBxkTiCOWP2IEj147uxJrGiVfSUR/P8UWMkf3bsT6Bc1b/nUk8lABLjhtdFzqFBYG/r4sNbQeQhbTCucd6TuuyRX+BsKw/DLLOztduqlhPySvpLNQzVMOWFDM76hvFaLzVhjMcZejYUJz49lPNMLAAJId+xV+kD4jkDz8OwgsdGF/lrRcqik0ZaPAnblO2NCMvQipRpF5ftLbVpotNVPyp74Ao1boRfmBzumjhwkHTu9CG+YEWs77hzpBYflaZREJM=
