language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- echo $GH_TOKEN
- yarn test
- yarn lint
env:
  global:
  - secure: IDil2tYwQdh4bzmaGsv8H3F8S1qAZL6BGAF9v3B10uJw4wCQmHl3LrCJ3WwUIOXW5Ueg2Ya+CznarjcJB0jLMDb48pQI6uV3KqZX4nnb0C/YRMjxtUhHJD4RrSXM5l6P/9Zb27TVG9ewc6sF119R4bHDvhJ/TkOzpEgMm8vE2TJWR8lHciffQ5YhKAb0inO46QyhW9uUGoesZf14SrE+Y4XB8+uPjI4oN8kJaQ+PNogsPNpEG1VjhfNaOGR6ChbOzWId9E7PxNPcYlpVkMeOozfc52bIPqJmpnpNq3dX25g7+QXva5+6KdMTkkGEze7WZLoap13sAzFfxeNBiAxLFUDxu/+kh0oTxYwY8SGFTVzraWNazLL0wh5rZ3LgufZ+etrK/vgb2tl4ghtfYZ7ZTP9kNg4IZe+0gG6wVwx8+pqHuduMFI9gHdV24xQoTWISp4tKYm2n2kTancLcWmhc7mEi9C+WyRMN242RHgmAnfE3Voja7CjOdauysl11VFvvABkKmyzzPI4Ic84fq9JIeYbZ1vQWLBg44HvkKrrxDhOBO7upgxFOQYscRiwac4zjBA/7UrigM2I8p2bKXz/lEy5oUa1WnOQ637y1oK9hJlY6SU+fQP0avjttDtCb5qSnHb44wIp3Mecg4R+kAGHVd2Zs6aZENP/0V4zOgWcbblc=
