language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- yarn test
- yarn lint
env:
  global:
  - secure: Ti5bJCuDVyV5RRMU6FEppVPzQvp7YwDHxISBpla7ZUpugszSYoiWJbbNUoqay44k0rzBpyJCYzki0asIH2/D2EDj2q138M4Zq3OtfiAyMkxeD3INub32ZROGk0Ob44fKyMCF2eDgIVObku8orvujV8/MDwFTCdPTEv3ZHMlZ9W9b/exk646eHUnDq20BOv5scV3yThCvcfRMOVOr2masNb7fW9tB64IBMR9B+h5vZRL4fMdB28xxNFXilbK9FPIIgvorICaWvxtJ/dZI8e8UA2YH1bDmcXEJz0lWwyyRgMOHqJIw1j2P4h3pc+WN/MUqHjItKnlHj/cKQXwl4lfV8RrGF0jLsUY+b8/MCB/1n2DVIgaiWymI+6dgIyj1LZDhmGNLhKdlYgPi3gOUKgbvYVYhk/Etp+jg9BmtSeZAbiWO9pAA55jfpBFus6weu3CtQjvqk0BcPG62q3A5uMx+6LaKUd8u0EYANQv8xJW9YtnIIPju3V7Q5zr7K8A+kEeRVDn3ZapYl+tTNihJVouYmxNCQAxkB8wzfvtJ0bPRaAlAmICsxron/Zi9oBv84l7Dg87lJbLCuPNlZiaZhqKji0g5o6cAYIBCEd1hZcq9m8+ugC6x9SvGyxJu3Ixd6e2zINxGsfI7HAeuGDKZXsgofAwNz6TIHOLyZ6KKD+UJ95o=
