language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- echo $GH_TOKEN
- yarn test
- yarn lint
env:
  global:
  - secure: Vy4mRMEnjNnHO8DMluojIxD4gxkubC2jCT9Zt7cm+1ST4QUdf1c1v9tdK28Z//LAiw5JqG77v2ATB9b6x7LSE6ESn9LDf5stZuWs9EuLlLoolRKa2wPuPG35mnVOB7fpws/BY9hefJEFxPlquxOkKcHyuidRiBrwziBKk/9Y1AhAokjPvv5ImzmDKqhmZRnz52oK+ylPL98lSdEpkuXQ4M27q6vDxAvY9PCSCXcdw7w6yHzxoBWQZf8BJdSgLQdSQyp/qHavLWJwiZri9+Gt42/aqn1txNZNJzj88lMXImtXK0C5tInL3vL1Z/bIiBEqrvc6uTiVEL+XwXJ8jpx+wLC9HLLMWEIKl3iQwV65wg4tYfVIVx1pzzP1/CX5LvSFyzm7c0QJbFeZlxC9km7mYQBQDkEVCr07SHGDnx/HZn/8lCGEpuBvnnOObW6DnPewJb9IQWI+MCbiZ/uoRxhD1JzgrZpdVexL9oiywNclD+3SimhbBzl4W/iwrOHxmWxFfYuU0uTWV93jT+nmmflvjoAanynRAtf8r4ViJVNlD1V32Dbxnt0YvK2LYJMaIl4DBo4kJ6o4zQM+Ei9dgT54q8S63/RK6FbAUvBCKuSXDZ4RL9JfFpgE8Y4UEpCOYrcUpugHlyQtTlqo22kR7FzfSLYWJAJ8xKKK2aSH92Y7FDo=
