language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- echo $GH_TOKEN
- yarn mock &
- '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./scripts/update-submodule.sh || echo ""'
script:
- echo $GH_TOKEN
- yarn test
- yarn lint
env:
  global:
    secure: 5xcnfQdD9LVfVmFIwOEYX71FWKXmb3j0KRw07P+xmHSkIw/5UhssMFgRH9yX1l2GursWXf4uszw7QG09GoTIar2bgVdnHvnoRJ7bQ+xf+q6dHaOrJ/cEU0NtfDrlUe63T0wwBzwsWRz96MvgND6pJGb7/GIR9pJFnuWWGb5N3B3EJFQnOn8PqK2G/quqORwKXuDJYa+qYz6cpPQNz4/0wFR3ndTJhtwej53cNOvw/zVmJ67bWPCaf6EjDql4GFyrSUOu0p5IontNWM+55OIm8xgPIWmYcvwmYW65W2ErPpJ5SERQ9uTrH4anaJIJRU82c8gkJLyerc2af+VEEs+w08+hLHMG9tRl0fGnkiKgDAmb6xDOV2T9zhdYZo8rNd/C57dy7owxBMLCJZWIE240KO5axCBqraBPoOJ3YumfUV/Yg0dzVrZutx7ERKHVihqhPMwJJ9ikYbgh/3OY2HJNijZ4LXkpytmTm9hLPwCYFcdyLIKaUMm61JiFBZIoAb+KCPwPckf+W9fvNg7ybI5WRpDkjZrsHKQKQ7ai4WQrd3mLlGnvZGTsyobs5J9VtiAwzTF9PcUXCTmV0XUbU0obwQ5ZYkCV4RtFyRgNM7gMLyGGQ/5yLiPXSK1kcZ32nmWcqPJaKP4/iQ4DA7++s5Nl/Qn9C2mIU6nrBKnDIc3VbSs=
